version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vos-postgres
    environment:
      POSTGRES_USER: vos
      POSTGRES_PASSWORD: vos_dev
      POSTGRES_DB: virtual_office_os
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: vos-redis
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    container_name: vos-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: vos-opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  postgres_data:
  minio_data:
  opensearch_data:
